# Site settings
title: "Adrien Eudes • French, Engineer, Entrepreneur"
email: adrien@eudes.co
description: "Hi, I'm Adrien Eudes. I'm a French Engineer & Entrepreneur, I currently live in Singapore. My passions: Maths, Data Science & Innovations. My mission: solving complexe problems with elegant methods using Science & Technology."
baseurl: ""
url: "http://adrien.eudes.co"
twitter_username: a_eud
github_username:  aeud

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: :compressed